server:
  servlet:
    context-path: /tools-management-api

spring:
  jpa.open-in-view: false
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://postgres:5432/tools_management}
    username: ${DATABASE_USER:tools_management_user}
    password: ${DATABASE_PASSWORD:SuperSecret}
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

integration:
  file-storage-api:
    url: ${INTEGRATION_FILE_STORAGE_API_URL:http://localhost}
    web-client-buffer-megabytes: ${INTEGRATION_FILE_STORAGE_API_BUFFER_MB:5}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

springdoc:
  use-fqn: true