insert into tools_brand (name) values ('Name');
insert into tools_brand (name) values ('Adagio');
insert into tools_brand (name) values ('Advanced');
insert into tools_brand (name) values ('AeroLatt');
insert into tools_brand (name) values ('AeroPres');
insert into tools_brand (name) values ('Afina');
insert into tools_brand (name) values ('Agraria');
insert into tools_brand (name) values ('Air Wick');
insert into tools_brand (name) values ('Alessi');
insert into tools_brand (name) values ('Alexande');
insert into tools_brand (name) values ('Alexandr');
insert into tools_brand (name) values ('All Amer');
insert into tools_brand (name) values ('All-Clad');
insert into tools_brand (name) values ('Allstate');
insert into tools_brand (name) values ('Alpine');
insert into tools_brand (name) values ('American');
insert into tools_brand (name) values ('AMIA');
insert into tools_brand (name) values ('Anchor H');
insert into tools_brand (name) values ('Andrea b');
insert into tools_brand (name) values ('Anne Ged');
insert into tools_brand (name) values ('Anolon');
insert into tools_brand (name) values ('Anthropo');
insert into tools_brand (name) values ('Antica F');
insert into tools_brand (name) values ('Applica');
insert into tools_brand (name) values ('Aquiesse');
insert into tools_brand (name) values ('Archipel');
insert into tools_brand (name) values ('Aroma');
insert into tools_brand (name) values ('Aromatiq');
insert into tools_brand (name) values ('Ashleigh');
insert into tools_brand (name) values ('Ashton S');
insert into tools_brand (name) values ('Aura Cac');
insert into tools_brand (name) values ('Authenti');
insert into tools_brand (name) values ('Auto Exp');
insert into tools_brand (name) values ('Avon');
insert into tools_brand (name) values ('Back to');
insert into tools_brand (name) values ('Badash');
insert into tools_brand (name) values ('Ball');
insert into tools_brand (name) values ('Baratza');
insert into tools_brand (name) values ('Bath & B');
insert into tools_brand (name) values ('Bayou Cl');
insert into tools_brand (name) values ('Beanpod');
insert into tools_brand (name) values ('Bella Cu');
insert into tools_brand (name) values ('Belleek');
insert into tools_brand (name) values ('Betty Cr');
insert into tools_brand (name) values ('Bey Berk');
insert into tools_brand (name) values ('Bialetti');
insert into tools_brand (name) values ('Biederma');
insert into tools_brand (name) values ('Black &');
insert into tools_brand (name) values ('Blendtec');
insert into tools_brand (name) values ('Bloomfie');
insert into tools_brand (name) values ('Blossom');
insert into tools_brand (name) values ('Blunt Po');
insert into tools_brand (name) values ('Bodum');
insert into tools_brand (name) values ('BonJour');
insert into tools_brand (name) values ('Bosch');
insert into tools_brand (name) values ('Braun');
insert into tools_brand (name) values ('Breadman');
insert into tools_brand (name) values ('Brentwoo');
insert into tools_brand (name) values ('Breville');
insert into tools_brand (name) values ('Brewster');
insert into tools_brand (name) values ('Brita');
insert into tools_brand (name) values ('Brooksto');
insert into tools_brand (name) values ('Brunschw');
insert into tools_brand (name) values ('Bulova');
insert into tools_brand (name) values ('BUNN');
insert into tools_brand (name) values ('Calphalo');
insert into tools_brand (name) values ('Calvin K');
insert into tools_brand (name) values ('Candle-L');
insert into tools_brand (name) values ('Cannon');
insert into tools_brand (name) values ('Capresso');
insert into tools_brand (name) values ('Carson H');
insert into tools_brand (name) values ('Casio');
insert into tools_brand (name) values ('CBK');
insert into tools_brand (name) values ('Champion');
insert into tools_brand (name) values ('Chantal');
insert into tools_brand (name) values ('Char-Bro');
insert into tools_brand (name) values ('Chemex');
insert into tools_brand (name) values ('CiCi Art');
insert into tools_brand (name) values ('Circulon');
insert into tools_brand (name) values ('Citrus M');
insert into tools_brand (name) values ('Claire B');
insert into tools_brand (name) values ('Coaster');
insert into tools_brand (name) values ('Coleman');
insert into tools_brand (name) values ('Collecto');
insert into tools_brand (name) values ('Colonial');
insert into tools_brand (name) values ('Conair');
insert into tools_brand (name) values ('Cooks Es');
insert into tools_brand (name) values ('Cooper C');
insert into tools_brand (name) values ('Copco');
insert into tools_brand (name) values ('Corelle');
insert into tools_brand (name) values ('CorningW');
insert into tools_brand (name) values ('Cornwall');
insert into tools_brand (name) values ('Crabtree');
insert into tools_brand (name) values ('Crofton');
insert into tools_brand (name) values ('Cuckoo');
insert into tools_brand (name) values ('Cuisinar');
insert into tools_brand (name) values ('Cuisinox');
insert into tools_brand (name) values ('Cuisipro');
insert into tools_brand (name) values ('Dale Tif');
insert into tools_brand (name) values ('Danielso');
insert into tools_brand (name) values ('Dansk');
insert into tools_brand (name) values ('DanyaB');
insert into tools_brand (name) values ('Darshan');
insert into tools_brand (name) values ('DayNa De');
insert into tools_brand (name) values ('Dazey');
insert into tools_brand (name) values ('DecoLav');
insert into tools_brand (name) values ('Deco Mes');
insert into tools_brand (name) values ('DeLonghi');
insert into tools_brand (name) values ('Deltana');
insert into tools_brand (name) values ('Demdaco');
insert into tools_brand (name) values ('Deni');
insert into tools_brand (name) values ('Designer');
insert into tools_brand (name) values ('Design T');
insert into tools_brand (name) values ('Disney');
insert into tools_brand (name) values ('Donvier');
insert into tools_brand (name) values ('Doughmak');
insert into tools_brand (name) values ('Dualit');
insert into tools_brand (name) values ('Ed Hardy');
insert into tools_brand (name) values ('Edward M');
insert into tools_brand (name) values ('Elegant');
insert into tools_brand (name) values ('Elements');
insert into tools_brand (name) values ('Elite');
insert into tools_brand (name) values ('Emerson');
insert into tools_brand (name) values ('Emson');
insert into tools_brand (name) values ('Escali');
insert into tools_brand (name) values ('Escentia');
insert into tools_brand (name) values ('Espressi');
insert into tools_brand (name) values ('eSpring');
insert into tools_brand (name) values ('Ethan Al');
insert into tools_brand (name) values ('Euro Cui');
insert into tools_brand (name) values ('Euro-Pro');
insert into tools_brand (name) values ('Excalibu');
insert into tools_brand (name) values ('Fabulous');
insert into tools_brand (name) values ('Fagor');
insert into tools_brand (name) values ('Farberwa');
insert into tools_brand (name) values ('Fascinat');
insert into tools_brand (name) values ('Fathead');
insert into tools_brand (name) values ('Febreze');
insert into tools_brand (name) values ('Fetco');
insert into tools_brand (name) values ('Flavia');
insert into tools_brand (name) values ('Floracra');
insert into tools_brand (name) values ('Fontanin');
insert into tools_brand (name) values ('Framed A');
insert into tools_brand (name) values ('Frette');
insert into tools_brand (name) values ('Frieling');
insert into tools_brand (name) values ('Frigidai');
insert into tools_brand (name) values ('Gaggia');
insert into tools_brand (name) values ('Ganz');
insert into tools_brand (name) values ('GE');
insert into tools_brand (name) values ('George F');
insert into tools_brand (name) values ('Gevalia');
insert into tools_brand (name) values ('Giftcraf');
insert into tools_brand (name) values ('Glade');
insert into tools_brand (name) values ('Global');
insert into tools_brand (name) values ('Godinger');
insert into tools_brand (name) values ('Gonesh');
insert into tools_brand (name) values ('Good Coo');
insert into tools_brand (name) values ('Gorham');
insert into tools_brand (name) values ('Grasslan');
insert into tools_brand (name) values ('Greenlea');
insert into tools_brand (name) values ('Green St');
insert into tools_brand (name) values ('Haier');
insert into tools_brand (name) values ('Hallmark');
insert into tools_brand (name) values ('Hamilton');
insert into tools_brand (name) values ('Handpres');
insert into tools_brand (name) values ('Hario');
insert into tools_brand (name) values ('Hearthsi');
insert into tools_brand (name) values ('Hello Ki');
insert into tools_brand (name) values ('Hem');
insert into tools_brand (name) values ('Henckels');
insert into tools_brand (name) values ('HERMES');
insert into tools_brand (name) values ('Hilason');
insert into tools_brand (name) values ('Hitachi');
insert into tools_brand (name) values ('Hobart');
insert into tools_brand (name) values ('HoMedics');
insert into tools_brand (name) values ('Home Int');
insert into tools_brand (name) values ('Hoosier');
insert into tools_brand (name) values ('Howard E');
insert into tools_brand (name) values ('Howard M');
insert into tools_brand (name) values ('Hunter');
insert into tools_brand (name) values ('Hurom');
insert into tools_brand (name) values ('Igloo');
insert into tools_brand (name) values ('IKEA');
insert into tools_brand (name) values ('Illumina');
insert into tools_brand (name) values ('IMAX');
insert into tools_brand (name) values ('Infinity');
insert into tools_brand (name) values ('InterDes');
insert into tools_brand (name) values ('Ives');
insert into tools_brand (name) values ('Jack LaL');
insert into tools_brand (name) values ('Jay Stro');
insert into tools_brand (name) values ('JCPenney');
insert into tools_brand (name) values ('Jenn-Air');
insert into tools_brand (name) values ('Jim Shor');
insert into tools_brand (name) values ('Joan Bak');
insert into tools_brand (name) values ('John Dee');
insert into tools_brand (name) values ('Jonathan');
insert into tools_brand (name) values ('Joyce Ch');
insert into tools_brand (name) values ('Joy Mang');
insert into tools_brand (name) values ('Juiceman');
insert into tools_brand (name) values ('Juicy Co');
insert into tools_brand (name) values ('Jura');
insert into tools_brand (name) values ('Jura-Cap');
insert into tools_brand (name) values ('Kalorik');
insert into tools_brand (name) values ('Karlsson');
insert into tools_brand (name) values ('Kassel');
insert into tools_brand (name) values ('Kate Spa');
insert into tools_brand (name) values ('Kenmore');
insert into tools_brand (name) values ('Keurig');
insert into tools_brand (name) values ('Kichler');
insert into tools_brand (name) values ('Kikkerla');
insert into tools_brand (name) values ('KitchenA');
insert into tools_brand (name) values ('K & K In');
insert into tools_brand (name) values ('Koolatro');
insert into tools_brand (name) values ('Krups');
insert into tools_brand (name) values ('Kyocera');
insert into tools_brand (name) values ('LaCuisin');
insert into tools_brand (name) values ('Lama Kas');
insert into tools_brand (name) values ('Lampe Be');
insert into tools_brand (name) values ('Langley');
insert into tools_brand (name) values ('La Pavon');
insert into tools_brand (name) values ('La Tee D');
insert into tools_brand (name) values ('Laura As');
insert into tools_brand (name) values ('Lavazza');
insert into tools_brand (name) values ('Lawrence');
insert into tools_brand (name) values ('Le Creus');
insert into tools_brand (name) values ('LEM');
insert into tools_brand (name) values ('Lenox');
insert into tools_brand (name) values ('Libbey');
insert into tools_brand (name) values ('Lilly Pu');
insert into tools_brand (name) values ('Little T');
insert into tools_brand (name) values ('Lladro');
insert into tools_brand (name) values ('Lodge');
insert into tools_brand (name) values ('Longaber');
insert into tools_brand (name) values ('Lumisour');
insert into tools_brand (name) values ('Lysol');
insert into tools_brand (name) values ('Magic Bu');
insert into tools_brand (name) values ('Magic Ch');
insert into tools_brand (name) values ('Marcato');
insert into tools_brand (name) values ('Margarit');
insert into tools_brand (name) values ('Marimekk');
insert into tools_brand (name) values ('Martha S');
insert into tools_brand (name) values ('Masterbu');
insert into tools_brand (name) values ('Mauviel');
insert into tools_brand (name) values ('Maxam');
insert into tools_brand (name) values ('Maxim');
insert into tools_brand (name) values ('MCS');
insert into tools_brand (name) values ('Medelco');
insert into tools_brand (name) values ('Melannco');
insert into tools_brand (name) values ('Melitta');
insert into tools_brand (name) values ('Method');
insert into tools_brand (name) values ('Metrokan');
insert into tools_brand (name) values ('Michael');
insert into tools_brand (name) values ('Miele');
insert into tools_brand (name) values ('Mikasa');
insert into tools_brand (name) values ('Mirro');
insert into tools_brand (name) values ('Missoni');
insert into tools_brand (name) values ('Mova');
insert into tools_brand (name) values ('Movado');
insert into tools_brand (name) values ('Mr. Coff');
insert into tools_brand (name) values ('Mr. Tea');
insert into tools_brand (name) values ('Nambe');
insert into tools_brand (name) values ('Nautica');
insert into tools_brand (name) values ('Nearly N');
insert into tools_brand (name) values ('Neonetic');
insert into tools_brand (name) values ('Nescafe');
insert into tools_brand (name) values ('Nespress');
insert into tools_brand (name) values ('Nest');
insert into tools_brand (name) values ('New Have');
insert into tools_brand (name) values ('New Leaf');
insert into tools_brand (name) values ('Ninja');
insert into tools_brand (name) values ('Nippon K');
insert into tools_brand (name) values ('Norpro');
insert into tools_brand (name) values ('Nostalgi');
insert into tools_brand (name) values ('Nuova Si');
insert into tools_brand (name) values ('NuTone');
insert into tools_brand (name) values ('Oleg Cas');
insert into tools_brand (name) values ('Olivia R');
insert into tools_brand (name) values ('Omega');
insert into tools_brand (name) values ('Oneida');
insert into tools_brand (name) values ('Oracal');
insert into tools_brand (name) values ('Oster');
insert into tools_brand (name) values ('OXO');
insert into tools_brand (name) values ('Ozium');
insert into tools_brand (name) values ('Pampered');
insert into tools_brand (name) values ('Panasoni');
insert into tools_brand (name) values ('Paragon');
insert into tools_brand (name) values ('Park Des');
insert into tools_brand (name) values ('PartyLit');
insert into tools_brand (name) values ('Pasta Ex');
insert into tools_brand (name) values ('Patch Ma');
insert into tools_brand (name) values ('Paula De');
insert into tools_brand (name) values ('Pendleto');
insert into tools_brand (name) values ('Pfaltzgr');
insert into tools_brand (name) values ('Philips');
insert into tools_brand (name) values ('Pier One');
insert into tools_brand (name) values ('Pillsbur');
insert into tools_brand (name) values ('Polder');
insert into tools_brand (name) values ('Pottery');
insert into tools_brand (name) values ('Powell');
insert into tools_brand (name) values ('Precious');
insert into tools_brand (name) values ('Presto');
insert into tools_brand (name) values ('Primula');
insert into tools_brand (name) values ('Prinz');
insert into tools_brand (name) values ('Privileg');
insert into tools_brand (name) values ('Proctor');
insert into tools_brand (name) values ('Progress');
insert into tools_brand (name) values ('Punch St');
insert into tools_brand (name) values ('PUR');
insert into tools_brand (name) values ('Pyrex');
insert into tools_brand (name) values ('Quartet');
insert into tools_brand (name) values ('Quoizel');
insert into tools_brand (name) values ('Rachael');
insert into tools_brand (name) values ('Ralph La');
insert into tools_brand (name) values ('Rancilio');
insert into tools_brand (name) values ('RAZ Impo');
insert into tools_brand (name) values ('Regal');
insert into tools_brand (name) values ('Renuzit');
insert into tools_brand (name) values ('Replogle');
insert into tools_brand (name) values ('Reston L');
insert into tools_brand (name) values ('Restorat');
insert into tools_brand (name) values ('Revere');
insert into tools_brand (name) values ('Rival');
insert into tools_brand (name) values ('River Ci');
insert into tools_brand (name) values ('Rizzy Ho');
insert into tools_brand (name) values ('Ronco');
insert into tools_brand (name) values ('RoomMate');
insert into tools_brand (name) values ('Root');
insert into tools_brand (name) values ('R.S.V.P.');
insert into tools_brand (name) values ('Rubberma');
insert into tools_brand (name) values ('Russ');
insert into tools_brand (name) values ('Russell');
insert into tools_brand (name) values ('SAC');
insert into tools_brand (name) values ('Saeco');
insert into tools_brand (name) values ('Saladmas');
insert into tools_brand (name) values ('Salton');
insert into tools_brand (name) values ('Samson');
insert into tools_brand (name) values ('Samsung');
insert into tools_brand (name) values ('Sandicas');
insert into tools_brand (name) values ('Sanyo');
insert into tools_brand (name) values ('Sarah Pe');
insert into tools_brand (name) values ('Satya');
insert into tools_brand (name) values ('Scentier');
insert into tools_brand (name) values ('Scentsy');
insert into tools_brand (name) values ('Schneide');
insert into tools_brand (name) values ('Sears');
insert into tools_brand (name) values ('Seda Fra');
insert into tools_brand (name) values ('Seiko');
insert into tools_brand (name) values ('Senseo');
insert into tools_brand (name) values ('Sensio');
insert into tools_brand (name) values ('SFERRA');
insert into tools_brand (name) values ('Shabby C');
insert into tools_brand (name) values ('Sharp');
insert into tools_brand (name) values ('Sharper');
insert into tools_brand (name) values ('Showtime');
insert into tools_brand (name) values ('Si Lucia');
insert into tools_brand (name) values ('SimpleHu');
insert into tools_brand (name) values ('Slatkin');
insert into tools_brand (name) values ('Slim Lin');
insert into tools_brand (name) values ('Snuggie');
insert into tools_brand (name) values ('Southern');
insert into tools_brand (name) values ('South Sh');
insert into tools_brand (name) values ('Spectrum');
insert into tools_brand (name) values ('SPI Home');
insert into tools_brand (name) values ('Stanley');
insert into tools_brand (name) values ('Starbuck');
insert into tools_brand (name) values ('Sterling');
insert into tools_brand (name) values ('Sunbeam');
insert into tools_brand (name) values ('Sunrise');
insert into tools_brand (name) values ('Swarovsk');
insert into tools_brand (name) values ('Swing');
insert into tools_brand (name) values ('Syroco');
insert into tools_brand (name) values ('Tag');
insert into tools_brand (name) values ('Target');
insert into tools_brand (name) values ('Tassimo');
insert into tools_brand (name) values ('Taylor');
insert into tools_brand (name) values ('Teleflor');
insert into tools_brand (name) values ('T-fal');
insert into tools_brand (name) values ('The Body');
insert into tools_brand (name) values ('The Magi');
insert into tools_brand (name) values ('The Nort');
insert into tools_brand (name) values ('Thermos');
insert into tools_brand (name) values ('Tiger');
insert into tools_brand (name) values ('TimeMist');
insert into tools_brand (name) values ('Timex');
insert into tools_brand (name) values ('Toastess');
insert into tools_brand (name) values ('Toastmas');
insert into tools_brand (name) values ('Tommy Hi');
insert into tools_brand (name) values ('Tools of');
insert into tools_brand (name) values ('Trend La');
insert into tools_brand (name) values ('Tribest');
insert into tools_brand (name) values ('Tripar');
insert into tools_brand (name) values ('Trudeau');
insert into tools_brand (name) values ('Tupperwa');
insert into tools_brand (name) values ('Umbra');